spring.application.name=News_ai

# ===== DataSource MySQL =====
spring.datasource.url=jdbc:mysql://localhost:3306/news_app?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=2004

# ===== JPA / Hibernate =====
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
server.servlet.context-path=/

spring.output.ansi.enabled=ALWAYS

# Hugging Face API pour UC3 - Résumer un article (IA)
huggingface.api.key=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

# NewsAPI Configuration
newsapi.api.key=197dfba4829042ae9e3eb47a9a535814
newsapi.api.base-url=https://newsapi.org/v2